// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swbuomxvxowdjpiquzsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3YnVvbXh2eG93ZGpwaXF1enNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTE5MDksImV4cCI6MjA2NTE4NzkwOX0.eFKi8FdONSUnwuwTZXUUfcqvbP_O4aOP-ov4v1PSlsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);